from datetime import date
from pathlib import Path

import yaml

from apiwatch import ingest
from apiwatch.cli import main
from apiwatch.models import ChangeRecord, load_records

FIX = Path(__file__).parent / "fixtures" / "ingest"
TODAY = date(2026, 9, 23)


def parse(key):
    vendor = ingest.SOURCES[key][0]
    return {(r.model, r.shutdown): r for r in ingest.parse_markdown((FIX / f"{key}.md").read_text(), vendor)}


def test_parse_dates():
    assert ingest.parse_date("June 15, 2026") == "2026-06-15"
    assert ingest.parse_date("Oct 1, 2026") == "2026-10-01"
    assert ingest.parse_date("Sept 3, 2026") == "2026-09-03"
    assert ingest.parse_date("2026‑03‑26") == "2026-03-26"   # non-breaking hyphens
    assert ingest.parse_date("No shutdown date announced") is None
    assert ingest.parse_date("Not sooner than January 1, 2028") is None


def test_parses_each_vendor_layout():
    a = parse("anthropic")
    assert set(a) == {("claude-test-2-20250101", "2026-05-01"), ("claude-test-1", "2025-06-01")}
    assert a[("claude-test-2-20250101", "2026-05-01")].replacements == ["claude-test-9"]
    assert a[("claude-test-2-20250101", "2026-05-01")].section.startswith("2026-03-01")  # history row preferred
    o = parse("openai")
    assert set(o) == {("tgpt-1-0613", "2026-10-23"), ("tgpt-2-mini", "2026-10-23"), ("tgpt-old", "2028-01-15")}
    assert o[("tgpt-1-0613", "2026-10-23")].aliases == ["tgpt-1", "tgpt-1-completions"]
    g = parse("google")
    assert set(g) == {("tgem-2-flash", "2026-06-01"), ("tgem-2-flash-001", "2026-06-01"),
                      ("tgem-2-pro-preview", "2025-12-02")}


def test_drafts_group_skip_old_and_covered_and_set_severity():
    rs = list(parse("openai").values())
    covered = ChangeRecord(id="c", vendor="OpenAI", surface="s", kind="model", severity="breaking",
                           effective="2026-10-23", summary="x", signatures=["tgpt-2-mini"])
    drafts = ingest.draft_records(rs, [covered], "2026-01-01", "https://example.com/deprecations", TODAY)
    by_id = {d["id"]: d for d in drafts}
    assert set(by_id) == {"openai-2026-10-23-legacy-test-snapshots", "openai-2028-01-15-far-future"}
    d = by_id["openai-2026-10-23-legacy-test-snapshots"]
    assert d["signatures"] == ["tgpt-1", "tgpt-1-0613", "tgpt-1-completions"]
    assert d["severity"] == "breaking" and d["verified"] is False
    assert "Announced 2026-06-01" in d["detail"] and "tgpt-1-0613 → tgpt-9-sol" in d["detail"]
    assert by_id["openai-2028-01-15-far-future"]["severity"] == "deprecation"
    for d in drafts:
        ChangeRecord(**d)


def test_cli_ingest_offline_writes_unverified_drafts_and_keeps_edits(tmp_path):
    out = tmp_path / "drafts"
    args = ["ingest", "--from-dir", str(FIX), "--records", str(tmp_path / "none"), "--out", str(out)]
    (tmp_path / "none").mkdir()
    assert main(args) == 0
    files = sorted(p.name for p in out.glob("*.yml"))
    assert "anthropic-2026-05-01-claude-test-2-model.yml" in files
    assert "google-2026-06-01-test-models.yml" in files
    assert not any("2025" in f.split("-")[1] for f in files)          # --since 2026-01-01
    recs = load_records(out)
    assert recs and not any(r.verified for r in recs)
    text = (out / "google-2026-06-01-test-models.yml").read_text()
    assert text.startswith("# DRAFT generated by `apiwatch ingest`")
    edited = out / "google-2026-06-01-test-models.yml"
    edited.write_text(text.replace("summary:", "summary: EDITED"))
    assert main(args) == 0
    assert "EDITED" in edited.read_text()                             # existing drafts are kept
    assert yaml.safe_load(edited.read_text())["signatures"] == ["tgem-2-flash", "tgem-2-flash-001"]


def test_committed_drafts_are_valid_unverified_and_not_published():
    drafts_dir = Path(__file__).parent.parent / "feed" / "drafts"
    if not drafts_dir.exists():
        return
    drafts = load_records(drafts_dir)
    assert not any(d.verified for d in drafts)     # an empty folder is fine: every draft may have been promoted
    record_ids = {r.id for r in load_records(Path(__file__).parent.parent / "feed" / "records")}
    assert not record_ids & {d.id for d in drafts}   # a draft is moved, not copied, when promoted


def test_fine_tunes_are_signed_as_code_writes_them_and_count_as_covered():
    from datetime import date
    from apiwatch.models import ChangeRecord
    r = ingest.Retirement("OpenAI", "ft-babbage-002", "2026-10-23", ["x-1"], "2026-04-22: Legacy")
    d = ingest.draft_records([r], [], "2026-01-01", "https://v.example", date(2026, 9, 24))
    assert d[0]["signatures"] == ["ft:babbage-002"]
    rec = ChangeRecord(id="o", vendor="OpenAI", surface="s", kind="model", severity="breaking", effective="2026-10-23",
                       summary="x", signatures=["ft:babbage-002"])
    assert ingest.covered(r, [rec])
